version: '3.8'
services: 
  #postgres db for local development
  kckr.postgres-database:
    image: postgres:14.1
    environment:
      POSTGRES_USER: "api"
      POSTGRES_PASSWORD: "api"
    ports:
        - "5432:5432"
    volumes:
     # - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql